Add support for multi-root workspaces
lunaryorn/gnome-search-providers-vscode pull request #15
Opened 2021-11-23 08:15 UTC by vianney

This patch adds multi-root workspaces saved as .code-workspace files to the results list.

Note: this is my first foray into rust-land, so any comment is more than welcome.

Closes #14

2021-11-23 18:05 UTC, lunaryorn requested changes
Thanks :pray:   I've left a few comments, and I'd like to ask you to add a `CHANGELOG.md` entry for this change and the corresponding issue.

2021-11-23 18:05 UTC, lunaryorn commented on src/main.rs
> +    workspace: Option<StorageOpenedPathsListEntryWorkspace>,
I presume it's either a folder, or a file, or a workspace?  So perhaps you could turn this into an untagged enum? See https://serde.rs/enum-representations.html#untagged

2021-11-23 18:05 UTC, lunaryorn commented on src/main.rs
> +struct StorageOpenedPathsListEntryWorkspace {
I think `WorkspaceEntry` would do :slightly_smiling_face:

2021-11-23 18:05 UTC, lunaryorn commented on src/main.rs
> +    config_path: Option<String>,
Why's this optional?  How would a workspace _without_ configuration path even work?  Does this really exist in VSCode?

2021-11-23 18:05 UTC, lunaryorn commented on src/main.rs
> +                    if let Some(workspace) = entry.workspace {
That's `entry.workspace.and_then(|w| w.config_path).or(entry.folder_uri)` :slightly_smiling_face:

2021-11-23 21:08 UTC, vianney commented
Thanks a lot for the review and letting me learn rust on the go. I have updated my branch with the requested changes, and updated the test suite as well.

2021-11-24 20:29 UTC, lunaryorn approved these changes

2021-11-24 20:30 UTC, merged

2021-11-24 20:30 UTC, lunaryorn commented
@vianney Thanks a bunch :pray: