Add support for official VSCode packages
lunaryorn/gnome-search-providers-vscode pull request #18
Opened 2022-01-07 20:24 UTC by Merrit

This should add support for all the official packages, which all seem to use the `code.desktop` naming.

2022-01-07 20:27 UTC, Merrit commented
I haven't been able to test the changes myself, because on openSUSE `sudo make install` is throwing errors I haven't been able to resolve -- even straight from source:

```
cargo build --release --locked
make: cargo: No such file or directory
make: *** [Makefile:12: build] Error 127
```

I looked into making an RPM, but the custom stuff it does beyond building a rust application complicates that a bit, and I just don't have the mental bandwidth to continue fighting it after several hours.

2022-01-08 07:33 UTC, lunaryorn commented
@Merrit I'm sorry that the Makefile doesn't work for you.  I'm not too happy about it either; any improvements or alternatives are very welcome :slightly_smiling_face:

2022-01-08 07:34 UTC, lunaryorn requested changes
Looks good so far.  Would you mind to add a `CHANGELOG.md` entry for this?

Please also rebase onto `master` to get the actions workflow running; I've just fixed the installation failure there. 

Thanks

2022-01-08 17:36 UTC, Merrit commented
> Looks good so far. Would you mind to add a `CHANGELOG.md` entry for this?
> 
> Please also rebase onto `master` to get the actions workflow running; I've just fixed the installation failure there.
> 
> Thanks

Done :+1: 

> I'm sorry that the Makefile doesn't work for you. I'm not too happy about it either; any improvements or alternatives are very welcome

I am not familiar with the syntax for makefiles.. the error it spit out didn't seem very helpful to me as to _what_ had actually gone wrong -- and googling the issue lead to a ton of possible problems.

It looks to me like basically it runs the rust-specific compiler, then copies the binary and config files to install locations? I don't know why the error wasn't more helpful, I would normally have done something like that in bash (and with bash I can even run it in a debugger).

2022-01-08 18:06 UTC, lunaryorn approved these changes

2022-01-08 19:21 UTC, lunaryorn commented
@Merrit Thanks a lot :pray: I'll make a new release with this change as soon as I can.

2022-01-08 19:21 UTC, merged