Adjusting LIBDIR in service files
lunaryorn/gnome-search-providers-vscode pull request #4
Opened 2021-04-21 16:10 UTC by SantoJambit

Resolves #3

2021-04-21 17:27 UTC, lunaryorn commented on Makefile
> +# Avoid double slash prefix
Just curious: Was this a problem in the files?

2021-04-21 17:28 UTC, lunaryorn commented
@SantoJambit Wow thanks a lot :clap:   Very kind of you to fix this, much obliged.

I have just a single question about the double-slash thing; I'd just like to understand what's going on there :innocent:

2021-04-22 07:56 UTC, SantoJambit commented on Makefile
> +# Avoid double slash prefix
The paths would contain a double slash at the start, which would then be written to the .service files and I wasn't sure if this was a problem. I noticed this double slash before during the normal installation log and I thought it would be cleaner if the first slash was removed.

2021-04-22 09:53 UTC, lunaryorn commented on Makefile
> +# Avoid double slash prefix
But does it do harm?  If it doesn't I'd prefer to do keep this simple; Make's already more than enough magic without having such tricks :innocent:

2021-04-22 09:55 UTC, lunaryorn commented on Makefile
> +# Avoid double slash prefix
That said, I noticed that your change is in fact wrong :grimacing: I'm sorry, I should've been more clear.

See my other comment.

2021-04-22 09:58 UTC, lunaryorn commented on Makefile
> +	sed "s:{LIBDIR}:$(LIBDIR):g" "systemd/de.swsnr.searchprovider.VSCode.service" > "target/systemd/de.swsnr.searchprovider.VSCode.service"
This is in fact not correct.

It substitutes `DESTDIR/PREFIX` into the service files but it should only be `$PREFIX`.  

By convention `PREFIX` denotes the root for the running software, whereas `DESTDIR` denotes where to install to.  The difference is important when packaging: A package build instruction (e.g. PKGBUILD, RPM spec, etc) would run `make DESTDIR=/temporary/package/directory PREFIX=/usr install`, and then bundle the package directory into the RPM or whatever, but the software would still run under `/usr` when installed.

If DESTDIR ends up in the files the software's broken at runtime.

2021-04-22 09:58 UTC, lunaryorn commented on Makefile
> +LIBDIR = $(SAFE_PREFIX)/lib
Please replace `SAFE_PREFIX` with `PREFIX` for libdir and datadir, and remove the whole SAFE_PREFIX thing.

2021-04-22 09:59 UTC, lunaryorn requested changes
I'm sorry but in fact this change wouldn't work; you'll need to fix a few things.

2021-04-22 09:59 UTC, lunaryorn commented on Makefile
> +	install -Dm644 -t $(DATADIR)/dbus-1/services target/dbus-1/de.swsnr.searchprovider.VSCode.service
Then add `$(DESTDIR)/` before each occurrence of LIBDIR, DATADIR and SEARCH_PROVIDERS_DIR.

2021-04-22 11:23 UTC, SantoJambit commented on Makefile
> +	sed "s:{LIBDIR}:$(LIBDIR):g" "systemd/de.swsnr.searchprovider.VSCode.service" > "target/systemd/de.swsnr.searchprovider.VSCode.service"
Didn't know that. Thanks for the info. Will correct

2021-04-22 11:27 UTC, SantoJambit commented
I've adjusted the PR to be as minimal of a change as possible.

2021-04-22 17:47 UTC, lunaryorn commented
> I've adjusted the PR to be as minimal of a change as possible.

Thanks 🙏

Much obliged for this fix 🙏

2021-04-22 17:48 UTC, merged