Support for version 1.55
lunaryorn/gnome-search-providers-vscode pull request #5
Opened 2021-04-21 16:17 UTC by SantoJambit

Adds support for the latest version of the vscode json format.

2021-04-21 16:26 UTC, SantoJambit commented
I'm new to rust, so let me know if I made a no-no.

2021-04-21 17:29 UTC, lunaryorn commented on src/main.rs
> +struct StorageOpenedPathsListEntries {
As this is just a single entry I'd rename it to `StorageOpenedPathsListEntry` :slightly_smiling_face:

Given that an entry is either a folder or a file I _think_ we could encode this as an enum:

```rust
enum StorageOpenedPathsListEntry {
  Folder { uri: String },
  File { uri: String},
}
```

and then put some `flatten` and/or `untagged` (see <https://serde.rs/attr-flatten.html>) and <https://serde.rs/enum-representations.html#untagged> respectively) in to  decode the structure in `storage.json`.

If you like you can try that for learning, but I'll also merge as is and refactor myself; getting this right probably takes a while for someone who's not familiar with Rust.

2021-04-21 17:34 UTC, lunaryorn requested changes
Many thanks for this pull request :hugs: 

I had a few minor nitpicks; I'd appreciate if you could address the one about `add_workspace`.

If you're short on time, just tell me and I'll merge and cut a new release, and refactor these things myself later.

2021-04-21 17:34 UTC, lunaryorn commented on src/main.rs
> +        if let Some(name) = url.split('/').last() {
I must admit that I don't like that this function can silently fail to add a namespace if there's no final name component (i.e. `.last()` returns `None`).  I know it's the same behaviour as before, but now that it's a function I think it deserves a bit more error handling.

Would you mind to make this function return a `Result<()>`, and return `Ok(())` if it got added and `Err(anyhow!("Failed to extract workspace name from uri {}", uri))` otherwise?

2021-04-21 17:42 UTC, lunaryorn commented
PS: This absolutely doesn't look like you've never used Rust before :+1: Very nice work indeed, many thanks :pray:

2021-04-22 08:54 UTC, SantoJambit commented on src/main.rs
> +struct StorageOpenedPathsListEntries {
I tried doing it with untagged (flatten didn't seem to fit), but I didn't find any way to define an else/any variant. So if microsoft decided that there would be one more type with for example "projectUri", the parser would throw an error, which is not ideal in this situation. Any idea how this could be solved?

2021-04-22 08:55 UTC, SantoJambit commented on src/main.rs
> +        if let Some(name) = url.split('/').last() {
If I do that, I need to handle the return value. How should that be done? Via map_err, error! and zbus::fdo::Error, like some other places?

2021-04-22 10:01 UTC, lunaryorn commented on src/main.rs
> +struct StorageOpenedPathsListEntries {
Let's leave it this way then; I haven't really thought about this in detail.

2021-04-22 12:01 UTC, SantoJambit commented on src/main.rs
> +        if let Some(name) = url.split('/').last() {
I've pushed some changes. Not sure if that's the preferred way to do this.

2021-04-22 20:03 UTC, closed without merging

2021-04-22 20:05 UTC, lunaryorn commented
@SantoJambit I didn't want to fail hard if a workspace couldn't be added and just log a warning instead, and I noticed a few refactoring opportunities, so I took the liberty to take your code and do the rest myself.

2021-04-23 07:03 UTC, SantoJambit commented
That's fine. Thanks!

2021-04-23 07:51 UTC, lunaryorn commented
I also made a new release, and also updated the AUR package (in case you're using Arch)

2021-04-23 08:11 UTC, SantoJambit commented
Thanks for the info, I missed that part of the readme I guess. Didn't work for me though. See #8